export const Strings = {
    welcome: 'WelCome',
    pleaseScanYourRFIDCard: 'Please scan your RFID card',
    chooseLanguage: 'Choose Language',
    english: 'English',
    hindi: 'Hindi',
    marathi: 'Marathi',
    cancel: 'Cancel',
    continue: 'Continue',
    areYouSureWantToCancelTheProcess: 'Are you sure want to cancel the process?',
    yourAccountBalance: 'Your Account Balance is',
    welcomeGourab: 'Welcome Gourab,',
    howCanWeHelpYouToday: 'How Can We Help You Today!',
    checkBalance: 'Check Balance',
    prescriptionSelection: 'Prescription Selection',
    selectPrescription: 'Select Prescription',
    selectRelationship: 'Select Relationship',
    self: 'Self',
    husband: 'Husband',
    wife: 'Wife',
    daughter: 'Daughter',
    son: 'Son',
    other: 'Other',
    currentBalance: 'Current Balance:',
    billingAmount: 'Billing Amount:',
    done: 'Done',
    viewBill: 'View Bill',
    doWantConfirmThisTransaction: 'Do you want to confirm\nthis transaction?',
    transactionCancelledDue: 'Transaction cancelled due to\ninsufficient balance',
    thankYouCustomerName: 'Thank You\nCustomer Name',
    collectYourMedicine: 'Collect your medicine',
    theMedicineDispatched: 'The medicine\nis being dispatched',
};

export default Strings;
